# Generated by Django 4.0.3 on 2022-04-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseId', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=200)),
                ('Descr', models.CharField(max_length=300)),
                ('Value', models.IntegerField()),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
